GET http://localhost:8090/api/users/getAllUsers

POST http://localhost:8090/api/users/create
Content-Type: application/json 

{
    "username": "aa",
    "password": "password1",
    "firstName": "a---",
    "lastName": "a=="

}